version: '3.5'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      mypupio: {}
  golfgeniuss:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '4174:4173'
    volumes:
      - '.env:/app/.env'
    networks:
      mypupio: {}
networks:
  mypupio:
    name: mypupio